### ISSUE TITLE
Source error (com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403)

### ISSUE THREAD

**Issue by bunmengteang** [ja2375/FluTube#9]
Hello, 
When loading video url, sometime i face this problem.
How to catch error or prevent this problem?

**Comment by ja2375** [comment]
Which . video are you trying to load? Is it copyrighted?
That error occurs when you try to load copyrighted videos.

It is written at the very top of the README:

> PLEASE NOTE: Embedding copyrighted videos is actually not possible. Please use flutter_youtube instead.

**Comment by bunmengteang** [comment]
But it just occur sometime, not every time of loading.
So it mean some time work, some time not work??

**Comment by ja2375** [comment]
Oh I see. Then it's not what I told you at first, sorry. 
I debugged that error and it seems to be some sort of race condition in the video_player plugin. Because the YouTube url is loading perfectly well when flutube is initialized. So I cannot be of more help :(

I have to add a callback that gets called when an error happens. It's not added yet, I have had no time. Apologies.

**Comment by ja2375** [comment]
Please update to 0.8.0 and see if this gets fixed for you. If not, please reopen the issue.
